In [1]:
import numpy as np

In [2]:
def shiftedqr(a):
    tol = 1.e-14
    kounttol = 500
    m = a.shape[0]
    n = m-1
    lam = np.zeros((m,1),dtype = complex)
    
    while n>0:
        kount = 0
        while max(abs(a[n,0:n])) > tol and kount < kounttol:
            kount += 1     # keep track of number of qr's
            mu = a[n,n]    # define shift mu
            q,r = np.linalg.qr( a - mu*np.eye(n+1) )
            a = np.dot(r,q) + mu*np.eye(n+1)
            
        if kount < kounttol:  # have isolated 1x1 block
            lam[n]=a[n,n] # declare eigenvalue
            n -= 1 # decrement n
            a = a[:n+1,:n+1] # deflate by 1
            
        else: # have isolated 2x2 block
            disc = complex(( a[-2,-2] - a[-1,-1] )**2 + 4*a[-1,-2]*a[-2,-1])
            #print('n_complex', n)
            lam[n]=( a[-2,-2] + a[-1,-1] + np.sqrt(disc))/2.
            lam[n-1]=( a[-2,-2] + a[-1,-1] - np.sqrt(disc))/2.
            n -= 2
            a = a[:n+1,:n+1] # deflate by 2
            
    if n==0: 
        lam[0] = a[0,0] # only a 1x1 block remains
    return lam

In [3]:
A = np.array([[-3, 3, 5], [1, -5, -5], [6, 6, 4]])
shiftedqr(A)

array([[-6.+0.j],
       [-2.+0.j],
       [ 4.+0.j]])

In [4]:
B = np.array([[3, 1, 2], [1, 3, -2], [2, 2, 6]])
shiftedqr(B)

array([[2.+0.j],
       [4.+0.j],
       [6.+0.j]])

In [5]:
C = np.array([[17, 1, 2], [1, 17, -2], [2, 2, 20]])
shiftedqr(C)

array([[16.+0.j],
       [18.+0.j],
       [20.+0.j]])

In [6]:
D = np.array([[-7, -8, 1], [17, 18, -1], [-8, -8, 2]])
shiftedqr(D)

array([[10.+0.j],
       [ 1.+0.j],
       [ 2.+0.j]])

In [7]:
E = np.array([[-1, 1, 3], [3, 3, -2], [-5, 2, 7]])
shiftedqr(E)

array([[2.99997556+0.00000000e+00j],
       [3.00001222-1.56707604e-05j],
       [3.00001222+1.56707604e-05j]])

In [8]:
F = np.array([[7, -33, -15], [2, 26, 7], [-4, -50, -13]])
shiftedqr(F)

array([[10.+0.j],
       [ 9.+0.j],
       [ 1.+0.j]])

In [9]:
G = np.array([[8, 0, 5], [-5, 3, -5], [10, 0, 13]])
shiftedqr(G)

array([[ 3.+0.j],
       [ 3.+0.j],
       [18.+0.j]])

In [10]:
H = np.array([[-3, -1, 1], [5, 3, -1], [-2, 2, 0]])
shiftedqr(H)

array([[ 2.+0.j        ],
       [-1.-1.73205081j],
       [-1.+1.73205081j]])

In [11]:
I = np.array([[4, 3, 1], [-5, -3, 0], [3, 2, 1]])
shiftedqr(I)

array([[8.8817842e-15-1.j],
       [8.8817842e-15+1.j],
       [2.0000000e+00+0.j]])

In [12]:
J = np.array([[3, 2, 0], [-4, -2, 1], [2, 1, 0]])
shiftedqr(J)

array([[-3.71924713e-15-1.j],
       [-3.71924713e-15+1.j],
       [ 1.00000000e+00+0.j]])

In [13]:
K = np.array([[7, 2, -4], [-8, 0, 7], [2, -1, -2]])
shiftedqr(K)

array([[2.-3.j],
       [2.+3.j],
       [1.+0.j]])

In [14]:
L = np.array([[11, 4, -2], [-10, 0, 5], [4, 1, 2]])
shiftedqr(L)

array([[4.-3.j],
       [4.+3.j],
       [5.+0.j]])